# Site settings
title: Fallbrook Research
description: Equity Anatlytics
disqus: fallbrookr
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site 

# User settings
username: Fallbrook 
user_description: At Fallbrook we're leveraging data science, quantitative finance, operational analytics, & machine learning methods to model systematic investement strategies, find signals in the noise, and generate Alpha.  Research for process workflow lifecycle including - alpha, beta, risk management, and execution & trade execution.
user_title: Research & Analytics
email: rob@fallbrook.com
twitter_username: Fallbrook_RA
github_username: d00d
gplus_username:  rdubnick

# Google-analytics
google-analytics:
  id: "UA-117521095-1"

exclude: ['package.json', 'src' , 'node_modules']
